Computing a raised to b mod c in logn time
rishabhgarg25699/Competitive-Programming pull request #108
Opened 2019-12-12 17:21 UTC by yashagarwal1999

Solved #101

2019-12-13 15:56 UTC, rishabhgarg25699 commented
@yashagarwal1999 Give proper indentation to the code

2019-12-13 16:44 UTC, yashagarwal1999 commented
Added Indentation to the code

2019-12-15 16:48 UTC, rishabhgarg25699 commented on fast_power.cpp
> +
No space required.

2019-12-29 04:58 UTC, rishabhgarg25699 requested changes
@yashagarwal1999 Please make correct indentation.

2019-12-29 04:58 UTC, rishabhgarg25699 commented on fast_power.cpp
> +      return 0;
Extra space

2019-12-29 04:58 UTC, rishabhgarg25699 commented on fast_power.cpp
> +   {
Extra space

2019-12-29 04:58 UTC, rishabhgarg25699 commented on fast_power.cpp
> +    if (k & 1)
4 line space after bracket.

2019-12-29 04:58 UTC, rishabhgarg25699 commented on fast_power.cpp
> +ll r = 1;
No indentation.

2020-01-12 08:46 UTC, closed without merging