addition of two ploynomial #67
rishabhgarg25699/Competitive-Programming pull request #136
Opened 2019-12-14 15:53 UTC by ashishugi

Add two polynomial using linked list .

2019-12-15 17:06 UTC, rishabhgarg25699 requested changes
@ashishugi Do proper indentation.

2019-12-19 12:14 UTC, ashishugi commented
hey could you be more specific , which indentation you are taking about

2019-12-19 19:57 UTC, rishabhgarg25699 commented on addition.cpp
> + struct node *next;
4 space inden.

2019-12-19 19:57 UTC, rishabhgarg25699 commented on addition.cpp
> +
Extra space

2019-12-19 19:57 UTC, rishabhgarg25699 commented on addition.cpp
> +     first=insert(first,p->coef,p->expo);
No indentation

2019-12-19 19:58 UTC, rishabhgarg25699 commented
Many indentations problem

2019-12-23 10:06 UTC, ashishugi commented
hey , i am not getting that , could u please get me the exact place??

2019-12-23 17:30 UTC, ashishugi commented
done this , please check out.

2019-12-24 13:01 UTC, rishabhgarg25699 commented on addition.cpp
> +   cout<<"enter the coefficient : "<<endl;
Where is 4 space ?

2019-12-24 13:01 UTC, rishabhgarg25699 commented on addition.cpp
> +
No extra space

2019-12-24 13:01 UTC, rishabhgarg25699 commented on addition.cpp
> +}
Many mistakes are there.

2020-01-20 16:00 UTC, closed without merging