close #175
rishabhgarg25699/Competitive-Programming pull request #238
Opened 2019-12-28 13:34 UTC by Roopam-mishra

Created segmented sieve in cpp as per the issue number #175

2019-12-29 05:01 UTC, rishabhgarg25699 commented on Segmented_Sieve.cpp
> +	segmentedSieve(100000001);
Do proper indentation,

2019-12-29 05:02 UTC, rishabhgarg25699 requested changes
Make Pull Request statement good

2019-12-29 12:56 UTC, Roopam-mishra commented
Done.
Do review the changes..

2019-12-30 05:51 UTC, rishabhgarg25699 approved these changes

2019-12-30 05:51 UTC, merged